language: ruby
cache: bundler # caching to speed up dependency installation
<<<<<<< add-links
rvm:
- 2.5
- jruby
=======
rvm: rvm
- replace me with rvm
>>>>>>> main
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
<<<<<<< add-links
- echo "Starting build!"
- bundle exec jekyll build
- echo "Finished build."
jobs:
  include:
    - stage: build
      script: script/build
    - stage: testlinks
      script: REPLACE-ME-WITH-HTML-PROOFER-SCRIPT
=======
- echo "Starting build! lol serieux"
>>>>>>> main
